blog/post/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms import StringField, TextAreaField, SubmitField, FileField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Заголовок', validators=[DataRequired()])
    content = TextAreaField('Статья', validators=[DataRequired()])
    picture = FileField('Изображение (png, jpg)', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Опубликовать')


class PostUpdateForm(FlaskForm):
    title = StringField('Заголовок', validators=[DataRequired()])
    content = TextAreaField('Статья', validators=[DataRequired()])
    picture = FileField('Изображение (png, jpg)', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Опубликовать')

blog/main/routes.py
from flask import Blueprint, render_template, request, url_for
from flask_login import login_required, current_user

from blog.models import Post, User

main = Blueprint('main', __name__, template_folder='templates')


@main.route('/')
def home():
    return render_template('main/index.html', title='Главная')


@main.route('/blog', methods=['POST', 'GET'])
@login_required
def blog():
    all_posts = Post.query.all()
    all_users = User.query.all()
    post = Post.query.get(current_user.id)
    if post:
        page = request.args.get('page', 1, type=int)
        posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=4)
        image_file = url_for('static',
                             filename=f'profile_pics/{current_user.username}/{post.image_post}')

        return render_template('main/blog.html', title='Блог', posts=posts, image_file=image_file,
                               all_posts=all_posts, all_users=all_users)
    else:
        return render_template('main/blog.html', title='Блог', nothing='Постов пока нет')


@main.route('/html_page')
def html_page():
    return render_template('main/html_page.html')


@main.route('/css_page')
def css_page():
    return render_template('main/css_page.html')


@main.route('/js_page')
def js_page():
    return render_template('main/js_page.html')


@main.route('/python_page')
def python_page():
    return render_template('main/python_page.html')


@main.route('/flask_page')
def flask_page():
    return render_template('main/flask_page.html')


@main.route('/django_page')
def django_page():
    return render_template('main/django_page.html')

blog/post/routes.py
from flask import (Blueprint, render_template, redirect, url_for, flash, abort, request)
from flask_login import current_user, login_required
from blog import db
from blog.models import Post
from blog.post.forms import PostForm, PostUpdateForm
from blog.user.utils import save_picture_post

posts = Blueprint('post', __name__, template_folder='templates')


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, image_post=form.picture.data, author=current_user)
        picture_file = save_picture_post(form.picture.data)
        post.image_post = picture_file
        db.session.add(post)
        db.session.commit()

        flash('Пост был опубликован!', 'success')
        return redirect(url_for('main.blog'))
    image_file = url_for('static',
                         filename=f'profile_pics/' + current_user.username + '/post_images/' + current_user.image_file)
    return render_template('post/create_post.html', title='Новая статья',
                           form=form, legend='Новая статья', image_file=image_file)


@posts.route('/post/<int:post_id>')
@login_required
def post(post_id):
    post = Post.query.get_or_404(post_id)
    image_file = url_for('static',
                         filename=f'profile_pics/' + post.author.username + '/post_images/' + post.image_post)
    return render_template('post/post.html', title=post.title, post=post, image_file=image_file)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)

    if post.author != current_user:
        abort(403)
    form = PostUpdateForm()
    if request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content

    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        if form.picture.data:
            post.image_post = save_picture_post(form.picture.data)
        db.session.commit()
        flash('Данный пост был обновлён', 'success')

        return redirect(url_for('post.post', post_id=post.id))

    image_file = url_for('static',
                         filename=f'profile_pics/{current_user.username}/post_images/{post.image_post}')

    return render_template('post/update_post.html', title='Обновить статью',
                           form=form, legend='Обновить статью', image_file=image_file, post=post)


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Данный пост был удален', 'success')
    return redirect(url_for('user.account'))

blog/user/routes.py
import os
import shutil
from datetime import datetime

import sqlalchemy
from flask import Blueprint, render_template, flash, url_for, request
from flask_login import current_user, logout_user, login_required, login_user
from werkzeug.utils import redirect

from blog import bcrypt, db
from blog.models import User, Post
from blog.user.forms import RegistrationForm, LoginForm, UpdateAccountForm, ResetPasswordForm, RequestResetForm
from blog.user.utils import save_picture, random_avatar, send_reset_email

users = Blueprint('user', __name__, template_folder='templates')


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.blog'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password,
                    image_file=random_avatar(form.username.data))
        db.session.add(user)
        db.session.commit()

        flash('Ваш аккаунт был создан. Вы можете войти на блог', 'success')
        return redirect(url_for('user.login'))
    return render_template('user/register.html', form=form, title='Регистрация', legend='Регистрация')


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.blog'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash(f'Вы вошли как пользователь {current_user.username}', 'info')
            return redirect(next_page) if next_page else redirect(url_for('user.account'))
        else:
            flash('Войти не удалось. Пожалуйста, проверьте электронную почту или пароль', 'danger')
    return render_template('user/login.html', form=form, title='Логин', legend='Войти')


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    user = User.query.filter_by(username=current_user.username).first()
    posts = Post.query.all()
    users = User.query.all()
    form = UpdateAccountForm()

    if request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    elif form.validate_on_submit():
        path_one = os.path.join(os.getcwd(), f'blog/static/profile_pics/{user.username}')
        path_two = os.path.join(os.getcwd(), f'blog/static/profile_pics/{form.username.data}')
        os.rename(path_one, path_two)
        current_user.username = form.username.data
        current_user.email = form.email.data

        if form.picture.data:
            current_user.image_file = save_picture(form.picture.data)
        else:
            form.picture.data = current_user.image_file

        db.session.commit()
        flash('Ваш аккаунт был обновлён!', 'success')
        return redirect(url_for('user.account'))
    image_file = url_for('static',
                         filename=f'profile_pics/' + current_user.username + '/account_img/' +
                                  current_user.image_file)
    return render_template('user/account.html', title='Аккаунт',
                           image_file=image_file, form=form, posts=posts, users=users, user=user)


@users.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user) \
        .order_by(Post.date_posted.desc()) \
        .paginate(page=page, per_page=3)

    return render_template('user/user_posts.html', title='Блог>', posts=posts, user=user)


@users.route('/user_delete/<string:username>', methods=['GET', 'POST'])
@login_required
def delete_user(username):
    try:
        user = User.query.filter_by(username=username).first_or_404()
        if user and user.id != 1:
            db.session.delete(user)
            db.session.commit()
            full_path = os.path.join(os.getcwd(), 'blog/static', 'profile_pics', user.username)
            shutil.rmtree(full_path)

            flash(f'Пользователь {username} был удалён!', 'info')
            return redirect(url_for('user.account'))

    except sqlalchemy.exc.IntegrityError:
        flash(f'У пользователя {username} есть контент!', 'warning')
        return redirect(url_for('user.account'))
    except FileNotFoundError:
        return redirect(url_for('user.account'))

    else:
        flash('Администрация!', 'info')
        return redirect(url_for('user.account'))


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.blog'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('На указанный емайл были отправлены инструкции по восстановлению пароля', 'info')
        return redirect(url_for('user.login'))
    return render_template('user/reset_request.html', form=form, title='Сброс пароля')


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.blog'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Не правильный или просроченный токен', 'warning')
        return redirect(url_for('user.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Ваш пароль был обновлён! Вы можете войти на блог', 'success')
        return redirect(url_for('user.login'))
    return render_template('user/reset_token.html', form=form, title='Сброс пароля')


@users.route('/logout')
def logout():
    current_user.last_seen = datetime.now()
    db.session.commit()
    logout_user()
    return redirect(url_for('main.home'))

blog/templates/create_post.html
{% extends 'layout.html' %}

{% block content %}
<div class="login_form new_post">
    <form action="" class="form_sign_in" enctype="multipart/form-data" method="POST">


        {{ form.hidden_tag() }}

        <legend class="legend">{{ legend }}</legend>


        <div class="invalid-feedback">
            {% for errors in form.title.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>

        {{ form.title(class='form-post-title', placeholder='Заголовок') }}

        {{ form.content(class='form-post-textarea', placeholder='Текст статьи') }}
        {{ form.picture }}


        {{ form.submit(class='btn_new_post') }}

    </form>
</div>
{% endblock content %}

blog/templates/html_page.html
{% extends 'layout.html' %}

{% block content %}

{% endblock %}

blog/templates/layout.html
<!DOCTYPE html>
<html lang="ru">
<head>

  <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/png" href="{{ url_for('static', filename='icon/favicon.ico') }}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/media_css.css')}}">
                <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}">


  {% block title %}

    <title>{{ title if title else 'Flask-blog' }}</title>

  {% endblock title %}

</head>

<body>
<div class="wrapper">

{% block menu %}
<header class="header">

    <div class="logo">
        <img src="{{ url_for('static', filename='img/logo.png') }}" alt="logo">

    </div>

    <ul class="main_menu">
{% if current_user.is_authenticated %}


        <li><a href="{{ url_for('main.home') }}">Главная</a></li>
        <li><a href="{{ url_for('main.blog') }}">Блог</a></li>
        <li><a href="{{ url_for('user.account') }}">Аккаунт</a></li>
        <li><a href="{{ url_for('user.logout') }}">Выход</a></li>

        <div class="online_status">
            <div class="online_user"></div>
            <div class="current_user"><small>{{ current_user.username }}</small></div>
        </div>


        {% else %}
        <li><a href="{{ url_for('main.home') }}">Главная</a></li>
        <li><a href="{{ url_for('user.register') }}">Регистрация</a></li>
        <li><a href="{{ url_for('user.login') }}">Логин</a></li>


        {% endif %}

    </ul>

</header>
{% endblock menu %}


    <div class="content">

<main role="main" class="#">
            <div class="row">
            <div class="col-md-12">
            {% with messages = get_flashed_messages(with_categories=True) %}

            {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}

            {% endwith %}

            {% block content %}
                {% endblock content %}
        </div>
        </div>

        </main>

    </div>


{% block main_page %}

{% endblock main_page %}

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>

{% block footer %}

    <footer class="footer">Все права защищены!<br>
        &#169; Терехов Михаил 2021

    </footer>

{% endblock footer %}
</div>
</body>
</html>

blog/templates/post.html
{% extends 'layout.html' %}

{% block content %}

<div class="wrapper_content">

    <div class="post">
        <img src="{{ url_for('static', filename='profile_pics/' + post.author.username + '/' + 'account_img' + '/' + post.author.image_file) }}"
             alt="" class="mr-3 mt-3 rounded-circle" style="width:40px;">

        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username)}}">{{ post.author.username
            }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%d.%m.%Y-%H.%M') }}</small>


        <h2 class="article-title"> {{ post.title }}</h2>
        <p class="article-content">{{ post.content }}</p>
        <img src="{{ image_file }}" alt="post_img"><br><br>
        <br>
        <a href="{{ url_for( 'main.blog' ) }}">Вернуться к блогу</a>


</div>
</div>

{% endblock %}

blog/templates/register.html
{% extends 'layout.html' %}

{% block content %}
<div class="register_form sign_in">
    <form action="" method="POST">

        {{ form.hidden_tag() }}
        <legend class="legend">{{ legend }}</legend>

        {% if form.username.errors %}
        {{ form.username(class='form-post-title is-invalid', placeholder='Имя пользователя') }}
        <div class="invalid-feedback">
            {% for errors in form.username.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.username(class='form-post-title', placeholder='Имя пользователя') }}
        {% endif %}

        {% if form.email.errors %}
        {{ form.email(class='form-post-title is-invalid', placeholder='Емайл') }}
        <div class="invalid-feedback">
            {% for errors in form.email.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.email(class='form-post-title', placeholder='Емайл') }}
        {% endif %}

        {% if form.password.errors %}
        {{ form.password(class='form-post-title is-invalid', placeholder='Пароль') }}
        <div class="invalid-feedback">
            {% for errors in form.password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.password(class='form-post-title', placeholder='Пароль') }}
        {% endif %}

        {% if form.confirm_password.errors %}
        {{ form.confirm_password(class='form-post-title is-invalid', placeholder='Подтвердите пароль') }}
        <div class="invalid-feedback">
            {% for errors in form.confirm_password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.confirm_password(class='form-post-title', placeholder='Подтвердите пароль') }}
        {% endif %}


        <div class="form-group_button">
           <div class="btn">
                {{ form.submit(class='btn_sign_in') }}
           </div>
              <small class="text-muted">
            Уже есть аккаунт? <a class='ml-2' href="{{ url_for('users.login')}}">Войти</a>
        </small>
        </div>

    </form>
    <div class="border-top">

    </div>
</div>



{% endblock content%}

blog/templates/user_posts.html
{% extends 'layout.html' %}

{% block content %}
<div class="wrapper_content">



    <h3>
        <img src="{{ url_for('static', filename='profile_pics/' + user.username + '/' + 'account_img' + '/' + user.image_file) }}"
             alt="" class="mr-3 mt-3 rounded-circle" style="width:40px;">

        <a class="mr-2" href="{{ url_for('users.user_posts', username=user.username)}}">{{ user.username }}</a>({{ posts.total }})</h3>

{% for post in posts.items %}


<div class="post">


    <h2><a class="article-title" style="font-size: 20px;" href="{{ url_for('post.post', post_id=post.id) }}">{{ post.title }}</a></h2>

</div>



{% endfor %}
<br>
            <a href="{{ url_for( 'main.blog' ) }}">Вернуться к блогу</a>
<br>
<br>
<div class="post_paginate">

    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=3) %}
        {% if page_num %}
            {% if posts.page == page_num %}
            <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% else %}
            <a class="btn btn-outline-success mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
    {% endif %}
    {% endfor %}
</div>
</div>

{% endblock %}