blog/user/routes.py
import os
import shutil
from datetime import datetime

import sqlalchemy
from flask import Blueprint, render_template, flash, url_for, request
from flask_login import current_user, logout_user, login_required, login_user
from werkzeug.utils import redirect

from blog import bcrypt, db
from blog.models import User, Post
from blog.user.forms import RegistrationForm, LoginForm, UpdateAccountForm, ResetPasswordForm, RequestResetForm
from blog.user.utils import save_picture, random_avatar, send_reset_email

users = Blueprint('user', __name__, template_folder='templates')


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.blog'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password,
                    image_file=random_avatar(form.username.data))
        db.session.add(user)
        db.session.commit()

        flash('Ваш аккаунт был создан. Вы можете войти на блог', 'success')
        return redirect(url_for('user.login'))
    return render_template('user/register.html', form=form, title='Регистрация', legend='Регистрация')


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.blog'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash(f'Вы вошли как пользователь {current_user.username}', 'info')
            return redirect(next_page) if next_page else redirect(url_for('user.account'))
        else:
            flash('Войти не удалось. Пожалуйста, проверьте электронную почту или пароль', 'danger')
    return render_template('user/login.html', form=form, title='Логин', legend='Войти')


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    user = User.query.filter_by(username=current_user.username).first()
    posts = Post.query.all()
    users = User.query.all()
    form = UpdateAccountForm()

    if request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    elif form.validate_on_submit():
        path_one = os.path.join(os.getcwd(), f'blog/static/profile_pics/{user.username}')
        path_two = os.path.join(os.getcwd(), f'blog/static/profile_pics/{form.username.data}')
        os.rename(path_one, path_two)
        current_user.username = form.username.data
        current_user.email = form.email.data

        if form.picture.data:
            current_user.image_file = save_picture(form.picture.data)
        else:
            form.picture.data = current_user.image_file

        db.session.commit()
        flash('Ваш аккаунт был обновлён!', 'success')
        return redirect(url_for('user.account'))
    image_file = url_for('static',
                         filename=f'profile_pics/' + current_user.username + '/account_img/' +
                                  current_user.image_file)
    return render_template('user/account.html', title='Аккаунт',
                           image_file=image_file, form=form, posts=posts, users=users, user=user)


@users.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user) \
        .order_by(Post.date_posted.desc()) \
        .paginate(page=page, per_page=3)

    return render_template('user/user_posts.html', title='Блог>', posts=posts, user=user)


@users.route('/user_delete/<string:username>', methods=['GET', 'POST'])
@login_required
def delete_user(username):
    try:
        user = User.query.filter_by(username=username).first_or_404()
        if user and user.id != 1:
            db.session.delete(user)
            db.session.commit()
            full_path = os.path.join(os.getcwd(), 'blog/static', 'profile_pics', user.username)
            shutil.rmtree(full_path)

            flash(f'Пользователь {username} был удалён!', 'info')
            return redirect(url_for('user.account'))

    except sqlalchemy.exc.IntegrityError:
        flash(f'У пользователя {username} есть контент!', 'warning')
        return redirect(url_for('user.account'))
    except FileNotFoundError:
        return redirect(url_for('user.account'))

    else:
        flash('Администрация!', 'info')
        return redirect(url_for('user.account'))


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.blog'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('На указанный емайл были отправлены инструкции по восстановлению пароля', 'info')
        return redirect(url_for('user.login'))
    return render_template('user/reset_request.html', form=form, title='Сброс пароля')


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.blog'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Не правильный или просроченный токен', 'warning')
        return redirect(url_for('user.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Ваш пароль был обновлён! Вы можете войти на блог', 'success')
        return redirect(url_for('user.login'))
    return render_template('user/reset_token.html', form=form, title='Сброс пароля')


@users.route('/logout')
def logout():
    current_user.last_seen = datetime.now()
    db.session.commit()
    logout_user()
    return redirect(url_for('main.home'))

blog/user/templates/user/account.html
{% extends 'layout.html' %}


{% block content %}

<div class="content-section">

    <div class="left_side">
    <h5>Зарегистрированные: </h5>
                    <ul>
                        {% for user in users: %}
                                                            {% if current_user.id == 1: %}

                            <li>
                                <div class="card_user">

                                     <img src="{{ url_for('static', filename='profile_pics/' + user.username + '/' + 'account_img' + '/' + user.image_file) }}"
             alt="" class="mr-3 mt-3 rounded-circle" style="width:40px;">
                                <a href="{{ url_for('user.user_posts', username=user.username)}}">{{ user.username }}</a>
  </div>
                            <h6 style="color:red"><a href="{{ url_for('user.delete_user', username=user.username) }}">удалить</a>?</h6>
            {% else %}
                                 <li> <a href="{{ url_for('user.user_posts', username=user.username)}}">{{ user.username }}</a>
{% endif %}

                            </li>

                        {% endfor %}
                    </ul>

</div>

<div class="list_posts" style="font-size: 18px;">
     <h5>Список статей: </h5>

    <ol>
        {% for post in user.posts %}
           <li><a href="{{ url_for('post.post', post_id=post.id)}}">{{ post.title }}</a></li>
        {% endfor %}
     </ol>
</div>
<div class="right_side">
<div class="card">

        <img class="card-body account-img " src="{{ image_file }}">
        <div class="media-body">
            <h4 class="account-heading">{{ current_user.username }}</h4>
            <p class="text-secondary">{{ current_user.email }}</p>
        </div>
    </div>

    <!-- FORM HERE -->
<div class="update_info">

        <form action="" method="POST" enctype="multipart/form-data">

            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-6 font_update">Обновление аккаунта</legend>
                <div class="form-group">
                    {{ form.username.label(class='form-control-label') }}

                    {% if form.username.errors %}
                    {{ form.username(class='form-control form-control-lg is-invalid') }}
                    <div class="invalid-feedback">
                        {% for errors in form.username.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.username(class='form-control form-control-lg') }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.email.label(class='form-control-label') }}
                    {% if form.email.errors %}
                    {{ form.email(class='form-control form-control-lg is-invalid') }}
                    <div class="invalid-feedback">
                        {% for errors in form.email.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.email(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {% if form.picture.errors %}
                   {{ form.picture(class='form-control form-control-lg is-invalid') }}
                    <div class="invalid-feedback">
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span><br>
                        {% endfor %}
                    </div>
                    {% else %}
                   {{ form.picture(class='form-control form-control-sm') }}

                    {% endif %}

                </div>

            </fieldset>
    <br>

            <div class="form-group">
                {{ form.submit(class='btn btn-outline-info') }}
            </div>

        </form>
    </div>
</div>


<!--        {{ user_all  }}-->

</div>

{% endblock content %}

blog/user/templates/user/login.html
{% extends 'layout.html' %}

{% block content %}
                        <div class="empty_block"></div>
                        <div class="empty_block"></div>

<div class="login_form log_in">
    <form action="" method="POST">

        {{ form.hidden_tag() }}
            <legend class="legend">{{ legend }}</legend>

            <div class="form-group">
                {% if form.email.errors %}
                {{ form.email(class='is-invalid', placeholder="Емайл") }}
                <div class="invalid-feedback">
                    {% for errors in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                    {{ form.email(class='form-post-title', placeholder="Емайл") }}
                {% endif %}
            </div>

                {% if form.password.errors %}
                {{ form.password(class='form-post-title is-invalid', placeholder='Пароль') }}
                <div class="invalid-feedback">
                    {% for errors in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                    {{ form.password(class='form-post-title', placeholder='Пароль') }}
                {% endif %}

            <div class="form-check">
                 {{ form.remember(class='form-check-input') }}
                 {{ form.remember.label(class='form-check-label') }}
            </div>

        </fieldset>




        <div class="form-group_button">

           <div class="btn"> {{ form.submit(class='btn_log_in') }}</div>
            <div class="border-top pt-2">


                 <small class="text-muted ml-2">
                <a href="{{ url_for('user.reset_request') }}">Забыли пароль?</a>
          </small>

    <small class="text-muted">
        <a class='ml-2' href="{{ url_for('user.register')}}"> Нужен аккаунт?</a>
    </small>
</div>

        </div>

    </form>
</div>



{% endblock %}

blog/user/templates/user/register.html
{% extends 'layout.html' %}

{% block content %}

<div class="register_form sign_in">
    <form action="" method="POST">

        {{ form.hidden_tag() }}
        <legend class="legend">{{ legend }}</legend>

        {% if form.username.errors %}
        {{ form.username(class='form-post-title is-invalid', placeholder='Имя пользователя') }}
        <div class="invalid-feedback">
            {% for errors in form.username.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.username(class='form-post-title', placeholder='Имя пользователя') }}
        {% endif %}

        {% if form.email.errors %}
        {{ form.email(class='form-post-title is-invalid', placeholder='Емайл') }}
        <div class="invalid-feedback">
            {% for errors in form.email.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.email(class='form-post-title', placeholder='Емайл') }}
        {% endif %}

        {% if form.password.errors %}
        {{ form.password(class='form-post-title is-invalid', placeholder='Пароль') }}
        <div class="invalid-feedback">
            {% for errors in form.password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.password(class='form-post-title', placeholder='Пароль') }}
        {% endif %}

        {% if form.confirm_password.errors %}
        {{ form.confirm_password(class='form-post-title is-invalid', placeholder='Подтвердите пароль') }}
        <div class="invalid-feedback">
            {% for errors in form.confirm_password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.confirm_password(class='form-post-title', placeholder='Подтвердите пароль') }}
        {% endif %}


        <div class="form-group_button">
           <div class="btn">
                {{ form.submit(class='btn_sign_in') }}
           </div>
              <small class="text-muted">
            <a class='ml-2' href="{{ url_for('user.login')}}">Уже есть аккаунт? </a>
        </small>
        </div>

    </form>
    <div class="border-top">

    </div>
</div>


</div>

{% endblock content%}

blog/user/templates/user/reset_request.html
{% extends 'layout.html' %}

{% block content %}

<div class="login_form reset_pass">
    <form action="" method="POST">

        {{ form.hidden_tag() }}
            <legend class="border-bottom mb-4">Сбросить пароль</legend>

            <div class="form-group">
                {% if form.email.errors %}
                {{ form.email(class='form-post-title is-invalid') }}
                <div class="invalid-feedback">
                    {% for errors in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                    {{ form.email(class='form-post-title', placeholder='Емайл') }}
                {% endif %}
            </div>



        <div class="form-group">
            {{ form.submit(class='btn_log_in', style="width: auto; padding-right: 10px;") }}
        </div>

    </form>
</div>



{% endblock content %}

blog/user/templates/user/reset_token.html
{% extends 'layout.html' %}

{% block content %}

<div class="login_form reset_token">
    <form action="" method="POST">

        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Сбросить пароль</legend>

            <div class="form-group">
                {% if form.password.errors %}
                {{ form.password(class='form-control form-control-lg is-invalid', placeholder="Пароль") }}
                <div class="invalid-feedback">
                    {% for errors in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                    {{ form.password(class='form-control form-control-lg', placeholder="Пароль") }}
                {% endif %}
            </div>
            <br>
            <div class="form-group">
                {% if form.confirm_password.errors %}
                {{ form.confirm_password(class='form-control form-control-lg is-invalid', placeholder="Подтвердите пароль") }}
                <div class="invalid-feedback">
                    {% for errors in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                    {{ form.confirm_password(class='form-control form-control-lg', placeholder="Подтвердите пароль") }}
                {% endif %}
            </div>

        </fieldset>

        <div class="form-group">
            {{ form.submit(class='btn_log_in') }}
        </div>

    </form>
</div>

{% endblock content %}

blog/user/templates/user/user_posts.html
{% extends 'layout.html' %}

{% block content %}
<div class="wrapper_content">


    <h3>
        <img src="{{ url_for('static', filename='profile_pics/' + user.username + '/' + 'account_img/' + user.image_file) }}"
             alt="" class="mr-3 mt-3 rounded-circle" style="width:40px;">

        <a class="mr-2" href="{{ url_for('user.user_posts', username=user.username)}}">{{ user.username }}</a>({{ posts.total }})</h3>

{% for post in posts.items %}


<div class="post">


    <h2><a class="article-title" style="font-size: 20px;" href="{{ url_for('post.post', post_id=post.id) }}">{{ post.title }}</a></h2>

</div>



{% endfor %}
<br>
            <a href="{{ url_for( 'main.blog' ) }}">Вернуться к блогу</a>
<br>
<br>
<div class="post_paginate">

    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=3) %}
        {% if page_num %}
            {% if posts.page == page_num %}
            <a class="btn btn-info mb-4" href="{{ url_for('user.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% else %}
            <a class="btn btn-outline-success mb-4" href="{{ url_for('user.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
    {% endif %}
    {% endfor %}
</div>
</div>

{% endblock %}