blog/post/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms import StringField, TextAreaField, SubmitField, FileField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Заголовок', validators=[DataRequired()])
    content = TextAreaField('Статья', validators=[DataRequired()])
    picture = FileField('Изображение (png, jpg)', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Опубликовать')


class PostUpdateForm(FlaskForm):
    title = StringField('Заголовок', validators=[DataRequired()])
    content = TextAreaField('Статья', validators=[DataRequired()])
    picture = FileField('Изображение (png, jpg)', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Опубликовать')

blog/post/routes.py
from flask import (Blueprint, render_template, redirect, url_for, flash, abort, request)
from flask_login import current_user, login_required
from blog import db
from blog.models import Post
from blog.post.forms import PostForm, PostUpdateForm
from blog.user.utils import save_picture_post

posts = Blueprint('post', __name__, template_folder='templates')


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, image_post=form.picture.data, author=current_user)
        picture_file = save_picture_post(form.picture.data)
        post.image_post = picture_file
        db.session.add(post)
        db.session.commit()

        flash('Пост был опубликован!', 'success')
        return redirect(url_for('main.blog'))
    image_file = url_for('static',
                         filename=f'profile_pics/' + current_user.username + '/post_images/' + current_user.image_file)
    return render_template('post/create_post.html', title='Новая статья',
                           form=form, legend='Новая статья', image_file=image_file)


@posts.route('/post/<int:post_id>')
@login_required
def post(post_id):
    post = Post.query.get_or_404(post_id)
    image_file = url_for('static',
                         filename=f'profile_pics/' + post.author.username + '/post_images/' + post.image_post)
    return render_template('post/post.html', title=post.title, post=post, image_file=image_file)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)

    if post.author != current_user:
        abort(403)
    form = PostUpdateForm()
    if request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content

    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        if form.picture.data:
            post.image_post = save_picture_post(form.picture.data)
        db.session.commit()
        flash('Данный пост был обновлён', 'success')

        return redirect(url_for('post.post', post_id=post.id))

    image_file = url_for('static',
                         filename=f'profile_pics/{current_user.username}/post_images/{post.image_post}')

    return render_template('post/update_post.html', title='Обновить статью',
                           form=form, legend='Обновить статью', image_file=image_file, post=post)


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Данный пост был удален', 'success')
    return redirect(url_for('user.account'))

blog/post/templates/post/create_post.html
{% extends 'layout.html' %}

{% block content %}
<div class="login_form new_post" >
    <form action="" class="form_sign_in" enctype="multipart/form-data" method="POST">


        {{ form.hidden_tag() }}

        <legend class="legend">{{ legend }}</legend>


        <div class="invalid-feedback">
            {% for errors in form.title.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>

        {{ form.title(class='form-post-title', placeholder='Заголовок') }}

        {{ form.content(class='form-post-textarea', placeholder='Текст статьи') }}
        {{ form.picture }}


        {{ form.submit(class='btn_new_post') }}

    </form>
</div>
{% endblock content %}

blog/post/templates/post/post.html
{% extends 'layout.html' %}

{% block content %}

<div class="post">
    <div class="user_post">
        <div class="user_info_single_post">
            <div class="left_side">
<img src="{{ url_for('static', filename='profile_pics/' + post.author.username + '/account_img/' + post.author.image_file) }}"
     alt="" class="mr-3 mt-3 rounded-circle" style="width:40px;">

<a class="mr-2" href="{{ url_for('user.user_posts', username=post.author.username)}}">{{ post.author.username }}</a>
<small class="text-muted">{{ post.date_posted.strftime('%d.%m.%Y-%H.%M') }}</small>
{% if post.author == current_user %}
</div>
            <div class="right_side">
<a class="btn btn-secondary btn-sm m-2" href="{{ url_for('post.update_post', post_id=post.id) }}">Обновить</a>
<button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    Удалить
</button>

{% endif %}
                </div>
            </div>

<h2 class="article-title" align="left"> {{ post.title }}</h2>
            <p class="article-content" align="left" >{{ post.content}}</p>
<img src="{{ image_file }}" alt="post_img">

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
     aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Удалить пост?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Удалить"></button>
            </div>
            <div class="modal-body">
                Вы точно хотите удалить этот пост?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                <form action="{{ url_for('post.delete_post', post_id=post.id) }}" method="post">
                    <input type="submit" class="btn btn-danger" value="Удалить">

                </form>
            </div>
        </div>
    </div>
</div>



{% endblock %}

blog/post/templates/post/update_post.html
{% extends 'layout.html' %}

{% block content %}
<div class="login_form">
    <form action="" class="form_sign_in" enctype="multipart/form-data" method="POST">


        {{ form.hidden_tag() }}

        <legend class="legend">{{ legend }}</legend>


        <div class="invalid-feedback">
            {% for errors in form.title.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>

        {{ form.title(class='form-post-title', placeholder='Обновить заголовок') }}

        {{ form.content(class='form-post-textarea', placeholder='Обновить текст статьи') }}
        {{ form.picture }}


        {{ form.submit(class='btn_new_post') }}

    </form>
</div>
{% endblock content %}