blog/main/routes.py
from flask import Blueprint, render_template, request, url_for
from flask_login import login_required, current_user

from blog.models import Post, User

main = Blueprint('main', __name__, template_folder='templates')


@main.route('/')
def home():
    return render_template('main/index.html', title='Главная')


@main.route('/blog', methods=['POST', 'GET'])
@login_required
def blog():
    all_posts = Post.query.all()
    all_users = User.query.all()
    post = Post.query.get(current_user.id)
    if post:
        page = request.args.get('page', 1, type=int)
        posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=4)
        image_file = url_for('static',
                             filename=f'profile_pics/{current_user.username}/{post.image_post}')

        return render_template('main/blog.html', title='Блог', posts=posts, image_file=image_file,
                               all_posts=all_posts, all_users=all_users)
    else:
        return render_template('main/blog.html', title='Блог', nothing='Постов пока нет')


@main.route('/html_page')
def html_page():
    return render_template('main/html_page.html')


@main.route('/css_page')
def css_page():
    return render_template('main/css_page.html')


@main.route('/js_page')
def js_page():
    return render_template('main/js_page.html')


@main.route('/python_page')
def python_page():
    return render_template('main/python_page.html')


@main.route('/flask_page')
def flask_page():
    return render_template('main/flask_page.html')


@main.route('/django_page')
def django_page():
    return render_template('main/django_page.html')

blog/main/templates/main/blog.html
{% extends 'layout.html' %}

{% block content %}

<div class="blog_content_area">


<div class="blog_content">
      {% for post in posts.items %}

    <div class="post">
        <div class="info_user_blog">
            <div class="info_user_blog_left">

                <img src="{{ url_for('static', filename='profile_pics/' + post.author.username + '/' + 'account_img' + '/' + post.author.image_file) }}"
                     alt="" class="mr-3 mt-3 rounded-circle" style="width:40px;">
                <a class="mr-2" href="{{ url_for('user.user_posts', username=post.author.username)}}">{{
                    post.author.username }}</a>
            </div>

            <div class="info_user_blog_right a">
                <small>{{ post.date_posted.strftime('%d.%m.%Y %H.%M') }}</small>
            </div>
        </div>

        <div class="posts_blog">
            <h2><a class="article-title" href="{{ url_for('post.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            {% if post.content|count >= 100 or post %}
            <p class="article-content" align="left">{{ post.content[0:300] }}...
                {% else %}
            <p class="article-content" align="left">{{ post.content }}</p>
            {% endif %}
        </div>
    </div>
    {% endfor %}


    <div class="post_paginate">

        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=3) %}
        {% if page_num %}
        {% if posts.page == page_num %}
        <a class="btn btn-info mb-4" href="{{ url_for('main.blog', page=page_num) }}">{{ page_num }}</a>
        {% else %}
        <a class="btn btn-outline-success mb-4" href="{{ url_for('main.blog', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
        {% else %}
        ...
        {% endif %}
        {% endfor %}
    </div>

</div>

<div class="info_posts_user">


        <h4>Статей на блоге: {{ posts.total }}</h4>


        {% for user in all_users %}
            {% if user.posts|count > 0 %}
            <p><a class="mr-2" href="{{ url_for('user.user_posts', username=user.username) }}">{{ user.username }}</a>({{ user.posts|count }})</p>
            {% endif%}
        {% endfor %}
               <button class="create_post_btn"><a href="{{ url_for('post.new_post') }}" class="btn_sign_in">Написать статью</a></button>

</div>
{% endblock content %}

blog/main/templates/main/css_page.html
{% extends 'layout.html' %}

{% block content %}

{% endblock %}

blog/main/templates/main/django_page.html
{% extends 'layout.html' %}

{% block content %}

{% endblock %}

blog/main/templates/main/flask_page.html
{% extends 'layout.html' %}

{% block content %}

{% endblock %}

blog/main/templates/main/html_page.html
{% extends 'layout.html' %}

{% block content %}

{% endblock %}

blog/main/templates/main/index.html
{% extends 'layout.html' %}


{% block main_page %}

<div class="wrapper">

    <div class="cascade_block">

        <div class="cascade_menu">
            <p class="info_name">Mike do IT - fullstack разработка</p>

            <div class="cascade_block_li">
                <ul>
                    <li class="checkmark"><a href="{{ url_for('main.html_page') }}">Html</a></li>
                    <li class="checkmark"><a href="{{ url_for('main.css_page') }}">Css</a></li>
                    <li class="checkmark"><a href="{{ url_for('main.python_page') }}">Python</a></li>
                    <li class="checkmark"><a href="{{ url_for('main.js_page') }}">Java Script</a></li>
                    <li class="checkmark"><a href="{{ url_for('main.flask_page') }}">Flask</a></li>
                    <li class="checkmark"><a href="{{ url_for('main.django_page') }}">Django</a></li>
                </ul>
            </div>
        </div>
    </div>


</div>

{% endblock main_page %}

blog/main/templates/main/js_page.html
{% extends 'layout.html' %}

{% block content %}

{% endblock %}

blog/main/templates/main/python_page.html
{% extends 'layout.html' %}

{% block content %}

{% endblock %}